//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesTool.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblCity", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblCity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cit_CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cit_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pro_ProvinceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cit_CityId {
            get {
                return this.Cit_CityIdField;
            }
            set {
                if ((this.Cit_CityIdField.Equals(value) != true)) {
                    this.Cit_CityIdField = value;
                    this.RaisePropertyChanged("Cit_CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cit_Name {
            get {
                return this.Cit_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Cit_NameField, value) != true)) {
                    this.Cit_NameField = value;
                    this.RaisePropertyChanged("Cit_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pro_ProvinceId {
            get {
                return this.Pro_ProvinceIdField;
            }
            set {
                if ((this.Pro_ProvinceIdField.Equals(value) != true)) {
                    this.Pro_ProvinceIdField = value;
                    this.RaisePropertyChanged("Pro_ProvinceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.HRWebServices")]
    public interface HRWebServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCities", ReplyAction="http://tempuri.org/HRWebServices/GetCitiesResponse")]
        HumanResourcesTool.ServiceReference.tblCity[] GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCities", ReplyAction="http://tempuri.org/HRWebServices/GetCitiesResponse")]
        System.Threading.Tasks.Task<HumanResourcesTool.ServiceReference.tblCity[]> GetCitiesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HRWebServicesChannel : HumanResourcesTool.ServiceReference.HRWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRWebServicesClient : System.ServiceModel.ClientBase<HumanResourcesTool.ServiceReference.HRWebServices>, HumanResourcesTool.ServiceReference.HRWebServices {
        
        public HRWebServicesClient() {
        }
        
        public HRWebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRWebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HumanResourcesTool.ServiceReference.tblCity[] GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<HumanResourcesTool.ServiceReference.tblCity[]> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
    }
}
