//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesTool.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblPosition", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblPosition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pos_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pos_PositionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_Description {
            get {
                return this.Pos_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Pos_DescriptionField, value) != true)) {
                    this.Pos_DescriptionField = value;
                    this.RaisePropertyChanged("Pos_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_PositionId {
            get {
                return this.Pos_PositionIdField;
            }
            set {
                if ((this.Pos_PositionIdField.Equals(value) != true)) {
                    this.Pos_PositionIdField = value;
                    this.RaisePropertyChanged("Pos_PositionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblDepartment", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblDepartment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Dep_DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dep_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dep_DepartmentId {
            get {
                return this.Dep_DepartmentIdField;
            }
            set {
                if ((this.Dep_DepartmentIdField.Equals(value) != true)) {
                    this.Dep_DepartmentIdField = value;
                    this.RaisePropertyChanged("Dep_DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dep_Name {
            get {
                return this.Dep_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Dep_NameField, value) != true)) {
                    this.Dep_NameField = value;
                    this.RaisePropertyChanged("Dep_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblTitle", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblTitle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tit_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tit_TitleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tit_Name {
            get {
                return this.Tit_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Tit_NameField, value) != true)) {
                    this.Tit_NameField = value;
                    this.RaisePropertyChanged("Tit_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tit_TitleId {
            get {
                return this.Tit_TitleIdField;
            }
            set {
                if ((this.Tit_TitleIdField.Equals(value) != true)) {
                    this.Tit_TitleIdField = value;
                    this.RaisePropertyChanged("Tit_TitleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblCountry", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblCountry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cuo_CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cuo_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince> tblProvincesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cuo_CountryId {
            get {
                return this.Cuo_CountryIdField;
            }
            set {
                if ((this.Cuo_CountryIdField.Equals(value) != true)) {
                    this.Cuo_CountryIdField = value;
                    this.RaisePropertyChanged("Cuo_CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuo_Name {
            get {
                return this.Cuo_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Cuo_NameField, value) != true)) {
                    this.Cuo_NameField = value;
                    this.RaisePropertyChanged("Cuo_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince> tblProvinces {
            get {
                return this.tblProvincesField;
            }
            set {
                if ((object.ReferenceEquals(this.tblProvincesField, value) != true)) {
                    this.tblProvincesField = value;
                    this.RaisePropertyChanged("tblProvinces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblProvince", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblProvince : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cou_CountryidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pro_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pro_ProvinceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HumanResourcesTool.ServiceReference.tblCountry tblCountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cou_Countryid {
            get {
                return this.Cou_CountryidField;
            }
            set {
                if ((this.Cou_CountryidField.Equals(value) != true)) {
                    this.Cou_CountryidField = value;
                    this.RaisePropertyChanged("Cou_Countryid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pro_Name {
            get {
                return this.Pro_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Pro_NameField, value) != true)) {
                    this.Pro_NameField = value;
                    this.RaisePropertyChanged("Pro_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pro_ProvinceId {
            get {
                return this.Pro_ProvinceIdField;
            }
            set {
                if ((this.Pro_ProvinceIdField.Equals(value) != true)) {
                    this.Pro_ProvinceIdField = value;
                    this.RaisePropertyChanged("Pro_ProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HumanResourcesTool.ServiceReference.tblCountry tblCountry {
            get {
                return this.tblCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.tblCountryField, value) != true)) {
                    this.tblCountryField = value;
                    this.RaisePropertyChanged("tblCountry");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblCity", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblCity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cit_CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cit_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pro_ProvinceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cit_CityId {
            get {
                return this.Cit_CityIdField;
            }
            set {
                if ((this.Cit_CityIdField.Equals(value) != true)) {
                    this.Cit_CityIdField = value;
                    this.RaisePropertyChanged("Cit_CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cit_Name {
            get {
                return this.Cit_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Cit_NameField, value) != true)) {
                    this.Cit_NameField = value;
                    this.RaisePropertyChanged("Cit_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pro_ProvinceId {
            get {
                return this.Pro_ProvinceIdField;
            }
            set {
                if ((this.Pro_ProvinceIdField.Equals(value) != true)) {
                    this.Pro_ProvinceIdField = value;
                    this.RaisePropertyChanged("Pro_ProvinceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblEmployee", Namespace="http://schemas.datacontract.org/2004/07/WCFResourceHumanServices")]
    [System.SerializableAttribute()]
    public partial class tblEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cit_CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Dep_DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Emp_AnualSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Emp_BirthOfDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Emp_EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Emp_HourlyRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Emp_PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Emp_PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Emp_StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Emp_TerminationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pos_PositionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tit_TitleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HumanResourcesTool.ServiceReference.tblCity tblCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HumanResourcesTool.ServiceReference.tblDepartment tblDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HumanResourcesTool.ServiceReference.tblPosition tblPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HumanResourcesTool.ServiceReference.tblTitle tblTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cit_CityId {
            get {
                return this.Cit_CityIdField;
            }
            set {
                if ((this.Cit_CityIdField.Equals(value) != true)) {
                    this.Cit_CityIdField = value;
                    this.RaisePropertyChanged("Cit_CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dep_DepartmentId {
            get {
                return this.Dep_DepartmentIdField;
            }
            set {
                if ((this.Dep_DepartmentIdField.Equals(value) != true)) {
                    this.Dep_DepartmentIdField = value;
                    this.RaisePropertyChanged("Dep_DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Address {
            get {
                return this.Emp_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_AddressField, value) != true)) {
                    this.Emp_AddressField = value;
                    this.RaisePropertyChanged("Emp_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Emp_AnualSalary {
            get {
                return this.Emp_AnualSalaryField;
            }
            set {
                if ((this.Emp_AnualSalaryField.Equals(value) != true)) {
                    this.Emp_AnualSalaryField = value;
                    this.RaisePropertyChanged("Emp_AnualSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Emp_BirthOfDate {
            get {
                return this.Emp_BirthOfDateField;
            }
            set {
                if ((this.Emp_BirthOfDateField.Equals(value) != true)) {
                    this.Emp_BirthOfDateField = value;
                    this.RaisePropertyChanged("Emp_BirthOfDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_CellPhone {
            get {
                return this.Emp_CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_CellPhoneField, value) != true)) {
                    this.Emp_CellPhoneField = value;
                    this.RaisePropertyChanged("Emp_CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Email {
            get {
                return this.Emp_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_EmailField, value) != true)) {
                    this.Emp_EmailField = value;
                    this.RaisePropertyChanged("Emp_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Emp_EmployeeId {
            get {
                return this.Emp_EmployeeIdField;
            }
            set {
                if ((this.Emp_EmployeeIdField.Equals(value) != true)) {
                    this.Emp_EmployeeIdField = value;
                    this.RaisePropertyChanged("Emp_EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_FirstName {
            get {
                return this.Emp_FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_FirstNameField, value) != true)) {
                    this.Emp_FirstNameField = value;
                    this.RaisePropertyChanged("Emp_FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Gender {
            get {
                return this.Emp_GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_GenderField, value) != true)) {
                    this.Emp_GenderField = value;
                    this.RaisePropertyChanged("Emp_Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Emp_HourlyRate {
            get {
                return this.Emp_HourlyRateField;
            }
            set {
                if ((this.Emp_HourlyRateField.Equals(value) != true)) {
                    this.Emp_HourlyRateField = value;
                    this.RaisePropertyChanged("Emp_HourlyRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_LastName {
            get {
                return this.Emp_LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_LastNameField, value) != true)) {
                    this.Emp_LastNameField = value;
                    this.RaisePropertyChanged("Emp_LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_Phone {
            get {
                return this.Emp_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_PhoneField, value) != true)) {
                    this.Emp_PhoneField = value;
                    this.RaisePropertyChanged("Emp_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Emp_Photo {
            get {
                return this.Emp_PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_PhotoField, value) != true)) {
                    this.Emp_PhotoField = value;
                    this.RaisePropertyChanged("Emp_Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emp_PostalCode {
            get {
                return this.Emp_PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Emp_PostalCodeField, value) != true)) {
                    this.Emp_PostalCodeField = value;
                    this.RaisePropertyChanged("Emp_PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Emp_StartDate {
            get {
                return this.Emp_StartDateField;
            }
            set {
                if ((this.Emp_StartDateField.Equals(value) != true)) {
                    this.Emp_StartDateField = value;
                    this.RaisePropertyChanged("Emp_StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Emp_TerminationDate {
            get {
                return this.Emp_TerminationDateField;
            }
            set {
                if ((this.Emp_TerminationDateField.Equals(value) != true)) {
                    this.Emp_TerminationDateField = value;
                    this.RaisePropertyChanged("Emp_TerminationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_PositionId {
            get {
                return this.Pos_PositionIdField;
            }
            set {
                if ((this.Pos_PositionIdField.Equals(value) != true)) {
                    this.Pos_PositionIdField = value;
                    this.RaisePropertyChanged("Pos_PositionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tit_TitleId {
            get {
                return this.Tit_TitleIdField;
            }
            set {
                if ((this.Tit_TitleIdField.Equals(value) != true)) {
                    this.Tit_TitleIdField = value;
                    this.RaisePropertyChanged("Tit_TitleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HumanResourcesTool.ServiceReference.tblCity tblCity {
            get {
                return this.tblCityField;
            }
            set {
                if ((object.ReferenceEquals(this.tblCityField, value) != true)) {
                    this.tblCityField = value;
                    this.RaisePropertyChanged("tblCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HumanResourcesTool.ServiceReference.tblDepartment tblDepartment {
            get {
                return this.tblDepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.tblDepartmentField, value) != true)) {
                    this.tblDepartmentField = value;
                    this.RaisePropertyChanged("tblDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HumanResourcesTool.ServiceReference.tblPosition tblPosition {
            get {
                return this.tblPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.tblPositionField, value) != true)) {
                    this.tblPositionField = value;
                    this.RaisePropertyChanged("tblPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HumanResourcesTool.ServiceReference.tblTitle tblTitle {
            get {
                return this.tblTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.tblTitleField, value) != true)) {
                    this.tblTitleField = value;
                    this.RaisePropertyChanged("tblTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.HRWebServices")]
    public interface HRWebServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/Login", ReplyAction="http://tempuri.org/HRWebServices/LoginResponse")]
        bool Login(string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/Login", ReplyAction="http://tempuri.org/HRWebServices/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetPositions", ReplyAction="http://tempuri.org/HRWebServices/GetPositionsResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblPosition> GetPositions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetPositions", ReplyAction="http://tempuri.org/HRWebServices/GetPositionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblPosition>> GetPositionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetDepartments", ReplyAction="http://tempuri.org/HRWebServices/GetDepartmentsResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblDepartment> GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetDepartments", ReplyAction="http://tempuri.org/HRWebServices/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblDepartment>> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetTitles", ReplyAction="http://tempuri.org/HRWebServices/GetTitlesResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblTitle> GetTitles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetTitles", ReplyAction="http://tempuri.org/HRWebServices/GetTitlesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblTitle>> GetTitlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCountries", ReplyAction="http://tempuri.org/HRWebServices/GetCountriesResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCountry> GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCountries", ReplyAction="http://tempuri.org/HRWebServices/GetCountriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCountry>> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetProvinces", ReplyAction="http://tempuri.org/HRWebServices/GetProvincesResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince> GetProvinces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetProvinces", ReplyAction="http://tempuri.org/HRWebServices/GetProvincesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince>> GetProvincesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetProvincesByCountry", ReplyAction="http://tempuri.org/HRWebServices/GetProvincesByCountryResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince> GetProvincesByCountry(int CountryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetProvincesByCountry", ReplyAction="http://tempuri.org/HRWebServices/GetProvincesByCountryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince>> GetProvincesByCountryAsync(int CountryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCities", ReplyAction="http://tempuri.org/HRWebServices/GetCitiesResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity> GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCities", ReplyAction="http://tempuri.org/HRWebServices/GetCitiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity>> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCitiesByProvince", ReplyAction="http://tempuri.org/HRWebServices/GetCitiesByProvinceResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity> GetCitiesByProvince(int ProvinceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCitiesByProvince", ReplyAction="http://tempuri.org/HRWebServices/GetCitiesByProvinceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity>> GetCitiesByProvinceAsync(int ProvinceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetProvinceIdByCityId", ReplyAction="http://tempuri.org/HRWebServices/GetProvinceIdByCityIdResponse")]
        int GetProvinceIdByCityId(int CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetProvinceIdByCityId", ReplyAction="http://tempuri.org/HRWebServices/GetProvinceIdByCityIdResponse")]
        System.Threading.Tasks.Task<int> GetProvinceIdByCityIdAsync(int CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCountryIdByProvinceId", ReplyAction="http://tempuri.org/HRWebServices/GetCountryIdByProvinceIdResponse")]
        int GetCountryIdByProvinceId(int ProvinceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetCountryIdByProvinceId", ReplyAction="http://tempuri.org/HRWebServices/GetCountryIdByProvinceIdResponse")]
        System.Threading.Tasks.Task<int> GetCountryIdByProvinceIdAsync(int ProvinceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetEmployees", ReplyAction="http://tempuri.org/HRWebServices/GetEmployeesResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee> GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetEmployees", ReplyAction="http://tempuri.org/HRWebServices/GetEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee>> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetEmployeesByLastAndFirstName", ReplyAction="http://tempuri.org/HRWebServices/GetEmployeesByLastAndFirstNameResponse")]
        System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee> GetEmployeesByLastAndFirstName(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetEmployeesByLastAndFirstName", ReplyAction="http://tempuri.org/HRWebServices/GetEmployeesByLastAndFirstNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee>> GetEmployeesByLastAndFirstNameAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetLastEmployeeId", ReplyAction="http://tempuri.org/HRWebServices/GetLastEmployeeIdResponse")]
        int GetLastEmployeeId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetLastEmployeeId", ReplyAction="http://tempuri.org/HRWebServices/GetLastEmployeeIdResponse")]
        System.Threading.Tasks.Task<int> GetLastEmployeeIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/insertDepartments", ReplyAction="http://tempuri.org/HRWebServices/insertDepartmentsResponse")]
        bool insertDepartments(HumanResourcesTool.ServiceReference.tblDepartment objDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/insertDepartments", ReplyAction="http://tempuri.org/HRWebServices/insertDepartmentsResponse")]
        System.Threading.Tasks.Task<bool> insertDepartmentsAsync(HumanResourcesTool.ServiceReference.tblDepartment objDepartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/insertEmployees", ReplyAction="http://tempuri.org/HRWebServices/insertEmployeesResponse")]
        bool insertEmployees(HumanResourcesTool.ServiceReference.tblEmployee objEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/insertEmployees", ReplyAction="http://tempuri.org/HRWebServices/insertEmployeesResponse")]
        System.Threading.Tasks.Task<bool> insertEmployeesAsync(HumanResourcesTool.ServiceReference.tblEmployee objEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetVerifyIfEmployeeExist", ReplyAction="http://tempuri.org/HRWebServices/GetVerifyIfEmployeeExistResponse")]
        bool GetVerifyIfEmployeeExist(int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetVerifyIfEmployeeExist", ReplyAction="http://tempuri.org/HRWebServices/GetVerifyIfEmployeeExistResponse")]
        System.Threading.Tasks.Task<bool> GetVerifyIfEmployeeExistAsync(int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetEmployeeInfo", ReplyAction="http://tempuri.org/HRWebServices/GetEmployeeInfoResponse")]
        HumanResourcesTool.ServiceReference.tblEmployee GetEmployeeInfo(int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/GetEmployeeInfo", ReplyAction="http://tempuri.org/HRWebServices/GetEmployeeInfoResponse")]
        System.Threading.Tasks.Task<HumanResourcesTool.ServiceReference.tblEmployee> GetEmployeeInfoAsync(int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/updateEmployees", ReplyAction="http://tempuri.org/HRWebServices/updateEmployeesResponse")]
        bool updateEmployees(HumanResourcesTool.ServiceReference.tblEmployee objEmployee, int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/updateEmployees", ReplyAction="http://tempuri.org/HRWebServices/updateEmployeesResponse")]
        System.Threading.Tasks.Task<bool> updateEmployeesAsync(HumanResourcesTool.ServiceReference.tblEmployee objEmployee, int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/deleteEmployees", ReplyAction="http://tempuri.org/HRWebServices/deleteEmployeesResponse")]
        bool deleteEmployees(int EmployeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRWebServices/deleteEmployees", ReplyAction="http://tempuri.org/HRWebServices/deleteEmployeesResponse")]
        System.Threading.Tasks.Task<bool> deleteEmployeesAsync(int EmployeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HRWebServicesChannel : HumanResourcesTool.ServiceReference.HRWebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRWebServicesClient : System.ServiceModel.ClientBase<HumanResourcesTool.ServiceReference.HRWebServices>, HumanResourcesTool.ServiceReference.HRWebServices {
        
        public HRWebServicesClient() {
        }
        
        public HRWebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRWebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRWebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRWebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string pass) {
            return base.Channel.Login(pass);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string pass) {
            return base.Channel.LoginAsync(pass);
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblPosition> GetPositions() {
            return base.Channel.GetPositions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblPosition>> GetPositionsAsync() {
            return base.Channel.GetPositionsAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblDepartment> GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblDepartment>> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblTitle> GetTitles() {
            return base.Channel.GetTitles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblTitle>> GetTitlesAsync() {
            return base.Channel.GetTitlesAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCountry> GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCountry>> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince> GetProvinces() {
            return base.Channel.GetProvinces();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince>> GetProvincesAsync() {
            return base.Channel.GetProvincesAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince> GetProvincesByCountry(int CountryId) {
            return base.Channel.GetProvincesByCountry(CountryId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblProvince>> GetProvincesByCountryAsync(int CountryId) {
            return base.Channel.GetProvincesByCountryAsync(CountryId);
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity> GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity>> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity> GetCitiesByProvince(int ProvinceId) {
            return base.Channel.GetCitiesByProvince(ProvinceId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblCity>> GetCitiesByProvinceAsync(int ProvinceId) {
            return base.Channel.GetCitiesByProvinceAsync(ProvinceId);
        }
        
        public int GetProvinceIdByCityId(int CityId) {
            return base.Channel.GetProvinceIdByCityId(CityId);
        }
        
        public System.Threading.Tasks.Task<int> GetProvinceIdByCityIdAsync(int CityId) {
            return base.Channel.GetProvinceIdByCityIdAsync(CityId);
        }
        
        public int GetCountryIdByProvinceId(int ProvinceId) {
            return base.Channel.GetCountryIdByProvinceId(ProvinceId);
        }
        
        public System.Threading.Tasks.Task<int> GetCountryIdByProvinceIdAsync(int ProvinceId) {
            return base.Channel.GetCountryIdByProvinceIdAsync(ProvinceId);
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee> GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee>> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee> GetEmployeesByLastAndFirstName(string searchString) {
            return base.Channel.GetEmployeesByLastAndFirstName(searchString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HumanResourcesTool.ServiceReference.tblEmployee>> GetEmployeesByLastAndFirstNameAsync(string searchString) {
            return base.Channel.GetEmployeesByLastAndFirstNameAsync(searchString);
        }
        
        public int GetLastEmployeeId() {
            return base.Channel.GetLastEmployeeId();
        }
        
        public System.Threading.Tasks.Task<int> GetLastEmployeeIdAsync() {
            return base.Channel.GetLastEmployeeIdAsync();
        }
        
        public bool insertDepartments(HumanResourcesTool.ServiceReference.tblDepartment objDepartment) {
            return base.Channel.insertDepartments(objDepartment);
        }
        
        public System.Threading.Tasks.Task<bool> insertDepartmentsAsync(HumanResourcesTool.ServiceReference.tblDepartment objDepartment) {
            return base.Channel.insertDepartmentsAsync(objDepartment);
        }
        
        public bool insertEmployees(HumanResourcesTool.ServiceReference.tblEmployee objEmployee) {
            return base.Channel.insertEmployees(objEmployee);
        }
        
        public System.Threading.Tasks.Task<bool> insertEmployeesAsync(HumanResourcesTool.ServiceReference.tblEmployee objEmployee) {
            return base.Channel.insertEmployeesAsync(objEmployee);
        }
        
        public bool GetVerifyIfEmployeeExist(int EmployeeId) {
            return base.Channel.GetVerifyIfEmployeeExist(EmployeeId);
        }
        
        public System.Threading.Tasks.Task<bool> GetVerifyIfEmployeeExistAsync(int EmployeeId) {
            return base.Channel.GetVerifyIfEmployeeExistAsync(EmployeeId);
        }
        
        public HumanResourcesTool.ServiceReference.tblEmployee GetEmployeeInfo(int EmployeeId) {
            return base.Channel.GetEmployeeInfo(EmployeeId);
        }
        
        public System.Threading.Tasks.Task<HumanResourcesTool.ServiceReference.tblEmployee> GetEmployeeInfoAsync(int EmployeeId) {
            return base.Channel.GetEmployeeInfoAsync(EmployeeId);
        }
        
        public bool updateEmployees(HumanResourcesTool.ServiceReference.tblEmployee objEmployee, int EmployeeId) {
            return base.Channel.updateEmployees(objEmployee, EmployeeId);
        }
        
        public System.Threading.Tasks.Task<bool> updateEmployeesAsync(HumanResourcesTool.ServiceReference.tblEmployee objEmployee, int EmployeeId) {
            return base.Channel.updateEmployeesAsync(objEmployee, EmployeeId);
        }
        
        public bool deleteEmployees(int EmployeeId) {
            return base.Channel.deleteEmployees(EmployeeId);
        }
        
        public System.Threading.Tasks.Task<bool> deleteEmployeesAsync(int EmployeeId) {
            return base.Channel.deleteEmployeesAsync(EmployeeId);
        }
    }
}
